export default interface Row {
  KLID: string;
  KLautocode: string;
  KLLastName: string;
  KLFirstName: string;
  KLGender: string;
  KLProfessionRaw: string;
  KLProfessionClustered: string;
  KLResidenceRaw: string;
  KLResidenceCZ: string;
  KLCriminalChargesFrom: string;
  KLCriminalChargesDateIN: string;
  KLCriminalChargesDateCaseworker: string;
  KLCriminalActionOffence: string;
  KLCriminalActionParagraph: string;
  KLPenaltyNoticeDate: string;
  KLFine: string;
  KLPrisonSentence: string;
  KLPublicationPress: string;
  KLFinePaid: string;
  KLCriminalChargesFromClear: string;
  KLCriminalChargesDEU: string;
  KLCriminalChargesDEUclustered: string;
  KLCriminalActionOffenceClustered: string;
  KLCriminalChargesDateINSort: string;
  KLPenaltyNoticeDateSort: string;
  KLFinePaidSort: string;
  KLBooksABC: string;
}
